// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRBlHVP7N9h8USQnbkBUACtvpd6s-23VY',
    appId: '1:707737182530:web:99b8bf12a7342c8d3ba8db',
    messagingSenderId: '707737182530',
    projectId: 'learnify-team',
    authDomain: 'learnify-team.firebaseapp.com',
    storageBucket: 'learnify-team.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8atSXSrUk2mh0PxBr0mJAIBUCVzIoyk',
    appId: '1:707737182530:android:d815196619d849883ba8db',
    messagingSenderId: '707737182530',
    projectId: 'learnify-team',
    storageBucket: 'learnify-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfT035DimRq-kaIju88i-MAKpEuMBeBaw',
    appId: '1:707737182530:ios:7688789ac13ae7203ba8db',
    messagingSenderId: '707737182530',
    projectId: 'learnify-team',
    storageBucket: 'learnify-team.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfT035DimRq-kaIju88i-MAKpEuMBeBaw',
    appId: '1:707737182530:ios:7688789ac13ae7203ba8db',
    messagingSenderId: '707737182530',
    projectId: 'learnify-team',
    storageBucket: 'learnify-team.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRBlHVP7N9h8USQnbkBUACtvpd6s-23VY',
    appId: '1:707737182530:web:5425d88e689d8c683ba8db',
    messagingSenderId: '707737182530',
    projectId: 'learnify-team',
    authDomain: 'learnify-team.firebaseapp.com',
    storageBucket: 'learnify-team.firebasestorage.app',
  );

}